site_name: Grid Backend service
site_description: Providing the description for the REST API that is being used for the App app
repo_url: https://github.com/tobias2910/grid-backend-service/
watch: [src]

nav:
  - Home:
      - Introduction: index.md
  - Documentation: reference/

theme:
  name: material
  features:
    - header.autohide
    - content.code.annotate
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light preference

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.snippets:
      check_paths: true

plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python

extra:
  social:
    - icon: material/web
      link: "https://tobiascaliskan.de"
      name: My website
    - icon: material/twitter
      link: https://twitter.com/CaliskanTobias
      name: Twitter
    - icon: material/github
      link: https://github.com/tobias2910/
      name: GitHub